name: Tests

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    ci:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                php: ['8.0', '8.1', '8.2', '8.3', '8.4']
                dependency-version: [prefer-lowest, prefer-stable]

        name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Setup Problem Matches
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install PHP dependencies
              run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress --ansi

            - name: Install Elasticsearch
              uses: ankane/setup-elasticsearch@v1

            - name: Install Typesense Database
              run: |
                  docker run -d \
                  -p 8108 \
                  --name typesense \
                  -v /tmp/typesense:/data \
                  typesense/typesense:28.0 \
                  --api-key=xyz \
                  --data-dir /data \
                  --enable-cors

            - name: Curl Typesense
              run: sleep 10 && curl http://localhost:8108/health

            - name: Unit Tests
              run: vendor/bin/phpunit --colors=always
